spring.application.name=notification-service

server.port = 9040
server.servlet.context-path=/notifications

spring.datasource.url=jdbc:postgresql://notification-db:5432/notificationsDB
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
