spring.application.name=user-service

server.port = 9020

jwt.secretKey = nkcjnaisuchhc89yf289fhjdsckjbe2uc92bcionsacondsv98c3h9v3jzbc236t478234rv3ovb

#SQL DB details
spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Eureka server config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka