spring.application.name=discovery-server

server.port=8761

# By default, the below properties are set to true and these are meant to register a particular service as eureka-client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
